// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Motores.IO.server.API.Data;

#nullable disable

namespace Motores.IO.server.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408120000_RemoverHistoricosMotores")]
    partial class RemoverHistoricosMotores
    {
    }
}
