// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Motores.IO.server.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Motores.IO.server.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212164814_AdicionarCamposCorrenteHistorico")]
    partial class AdicionarCamposCorrenteHistorico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Motores.IO.server.API.Models.Alarme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("DataReconhecimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MotorId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotorNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Reconhecido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UsuarioReconhecimentoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MotorId");

                    b.HasIndex("Reconhecido");

                    b.HasIndex("Timestamp");

                    b.ToTable("Alarmes");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.HistoricoMotor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Corrente")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CorrenteMaxima")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CorrenteMedia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CorrenteMinima")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("MotorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tensao")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MotorId");

                    b.HasIndex("Timestamp");

                    b.ToTable("HistoricosMotores");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Motor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("CorrenteNominal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DataEstimadaProximaManutencao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Histerese")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Horimetro")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("HorimetroProximaManutencao")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PercentualCorrenteMaxima")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("PlantaId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PosicaoX")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PosicaoY")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Potencia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RegistroLocal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegistroModBus")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("desligado");

                    b.Property<decimal>("Tensao")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("PlantaId");

                    b.ToTable("Motores");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("MotorId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroOS")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MotorId");

                    b.HasIndex("NumeroOS")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("OrdensServico");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Planta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApiToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ApiTokenGeradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApiToken")
                        .IsUnique()
                        .HasFilter("\"ApiToken\" IS NOT NULL");

                    b.HasIndex("ClienteId", "Codigo")
                        .IsUnique();

                    b.ToTable("Plantas");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.RelatorioOS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Anexos")
                        .HasColumnType("text");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OSId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Tecnico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OSId");

                    b.ToTable("RelatoriosOS");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.TemaCliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfiguracaoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("TemasCliente");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.TemaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConfiguracaoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("TemasUsuario");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("visualizador");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.UsuarioPlanta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("PlantaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlantaId");

                    b.HasIndex("UsuarioId", "PlantaId")
                        .IsUnique();

                    b.ToTable("UsuariosPlantas");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Alarme", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Motor", "Motor")
                        .WithMany("Alarmes")
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.HistoricoMotor", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Motor", "Motor")
                        .WithMany("Historicos")
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Motor", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Planta", "Planta")
                        .WithMany("Motores")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Planta");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.OrdemServico", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Motor", "Motor")
                        .WithMany("OrdensServico")
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Planta", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Cliente", "Cliente")
                        .WithMany("Plantas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.RelatorioOS", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.OrdemServico", "OrdemServico")
                        .WithMany("Relatorios")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.TemaCliente", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Cliente", "Cliente")
                        .WithOne("Tema")
                        .HasForeignKey("Motores.IO.server.API.Models.TemaCliente", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.TemaUsuario", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Usuario", "Usuario")
                        .WithOne("Tema")
                        .HasForeignKey("Motores.IO.server.API.Models.TemaUsuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Usuario", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.UsuarioPlanta", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Planta", "Planta")
                        .WithMany("UsuariosPlantas")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motores.IO.server.API.Models.Usuario", "Usuario")
                        .WithMany("UsuariosPlantas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Cliente", b =>
                {
                    b.Navigation("Plantas");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Motor", b =>
                {
                    b.Navigation("Alarmes");

                    b.Navigation("Historicos");

                    b.Navigation("OrdensServico");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.OrdemServico", b =>
                {
                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Planta", b =>
                {
                    b.Navigation("Motores");

                    b.Navigation("UsuariosPlantas");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Usuario", b =>
                {
                    b.Navigation("Tema");

                    b.Navigation("UsuariosPlantas");
                });
#pragma warning restore 612, 618
        }
    }
}
