// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Motores.IO.server.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Motores.IO.server.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Motores.IO.server.API.Models.Alarme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataReconhecimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("MotorId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotorNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Reconhecido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UsuarioReconhecimentoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MotorId");

                    b.HasIndex("Reconhecido");

                    b.HasIndex("Timestamp");

                    b.ToTable("Alarmes");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.HistoricoMotor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Corrente")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("MotorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Temperatura")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tensao")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MotorId");

                    b.HasIndex("Timestamp");

                    b.ToTable("HistoricosMotores");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Motor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CorrenteAtual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CorrenteInicial")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CorrenteNominal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEstimadaProximaManutencao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Histerese")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Horimetro")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("HorimetroProximaManutencao")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MediaHorasDia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MediaHorasMes")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MediaHorasSemana")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PercentualCorrenteMaxima")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PosicaoX")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PosicaoY")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Potencia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("desligado");

                    b.Property<decimal>("Tensao")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TotalOS")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Motores");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("MotorId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroOS")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("MotorId");

                    b.HasIndex("NumeroOS")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("OrdensServico");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.RelatorioOS", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Anexos")
                        .HasColumnType("text");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OSId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Tecnico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OSId");

                    b.ToTable("RelatoriosOS");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Alarme", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Motor", "Motor")
                        .WithMany("Alarmes")
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.HistoricoMotor", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Motor", "Motor")
                        .WithMany("Historicos")
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.OrdemServico", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.Motor", "Motor")
                        .WithMany("OrdensServico")
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Motor");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.RelatorioOS", b =>
                {
                    b.HasOne("Motores.IO.server.API.Models.OrdemServico", "OrdemServico")
                        .WithMany("Relatorios")
                        .HasForeignKey("OSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.Motor", b =>
                {
                    b.Navigation("Alarmes");

                    b.Navigation("Historicos");

                    b.Navigation("OrdensServico");
                });

            modelBuilder.Entity("Motores.IO.server.API.Models.OrdemServico", b =>
                {
                    b.Navigation("Relatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
